name: Selenium Scraper

on:
  push: # Trigger on push, you can change this to a schedule

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify your Python version

    - name: Install Python Dependencies
      run: |
        pip install selenium
        pip install bs4

    - name: Download and Set up ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y libglib2.0-0 libnss3 libgconf-2-4 libfontconfig1
        CHROME_DRIVER_URL="https://drive.google.com/file/d/1hX5RZQPmJQ1VcTaYq5nWAnYWvUJOScug/view?usp=sharing"
        wget -N $CHROME_DRIVER_URL -O chromedriver_linux64.zip
        unzip chromedriver_linux64.zip -d ~/
        sudo mv -f ~/chromedriver /usr/local/share/
        sudo chmod +x /usr/local/share/chromedriver
        sudo ln -sf /usr/local/share/chromedriver /usr/local/bin/chromedriver
        sudo ln -sf /usr/local/share/chromedriver /usr/bin/chromedriver

    - name: Run Selenium Script
      run: python main.py  # Replace with the path to your script
