name: Selenium Scraper

on:
  push: # Trigger on push, you can change this to a schedule

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify your Python version

    - name: Install Python Dependencies
      run: |
        pip install selenium
        pip install bs4

    - name: Set up ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y libglib2.0-0 libnss3 libgconf-2-4 libfontconfig1
        CHROME_DRIVER_VERSION="120.0.6099.109"
        CHROME_DRIVER_URL="https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${CHROME_DRIVER_VERSION}/linux64/chromedriver-linux64.zip"
        wget -N $CHROME_DRIVER_URL -P ~/
        unzip ~/chromedriver-linux64.zip -d ~/chromedriver-linux64
        sudo mv -f ~/chromedriver-linux64/chromedriver /usr/local/share/
        sudo chmod +x /usr/local/share/chromedriver
        sudo ln -sf /usr/local/share/chromedriver /usr/local/bin/chromedriver
        sudo ln -sf /usr/local/share/chromedriver /usr/bin/chromedriver

    - name: Run Selenium Script
      run: python main.py  # Replace with the path to your script
