name: Selenium Scraper

on:
  push: # Trigger on push, you can change this to a schedule

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Python Dependencies
      run: |
        pip install selenium
        pip install bs4
        pip install pydrive

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Download and Set up ChromeDriver
      run: |
        CHROME_DRIVER_URL="https://drive.google.com/uc?export=download&id=1H6p3Pm9LNlUvBtjCQoeyREJmFdSxnkE_"
        wget -N $CHROME_DRIVER_URL -O chromedriver.zip
        unzip chromedriver.zip -d ~/
        sudo mv -f ~/chromedriver /usr/local/share/
        sudo chmod +x /usr/local/share/chromedriver
        sudo ln -sf /usr/local/share/chromedriver /usr/local/bin/chromedriver
        sudo ln -sf /usr/local/share/chromedriver /usr/bin/chromedriver

    - name: Run Selenium Script
      run: python main.py  # Make sure this script updates OutputResults.csv

    - name: Commit and Push Output File
      env:
        ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global user.name 'SoloSaudiDeveloper'
        git config --global user.email 'SoloSaudiDeveloper@gmail.com'
        git add OutputResults.csv
        git commit -m "Update output CSV file" || echo "No changes to commit"
        git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/SoloSaudiDeveloper/shares.git main
